name: Build Checks

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node v18
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - run: npm i
    - run: npm run lint