name: ci/cd

on:
  push:
    branches:
      - "main"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          CMS_API: ${{ secrets.CMS_API }}
        with:
          context: .
          push: true
          tags: imamsyahid/dev:latest
          secrets: |
            "aws_region=${{secrets.AWS_REGION}}"
            "aws_access_key_id=${{secrets.AWS_ACCESS_KEY}}"
            "aws_secret_access_key=${{secrets.AWS_SECRET_ACCESS_KEY}}"
            "aws_bucket=${{secrets.AWS_BUCKET}}"
  deployment:
    name: Deploy to imamsyahid.dev
    needs: build-image
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://www.imamsyahid.dev
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            bash scripts/web.sh
